export const copy = {
  th: {
    brand: 'melearn chat',
    tagline: 'คุยกับครูที่ใช่ เรียนรู้ในแบบคุณ',
    intro: 'เลือกครู ถามสิ่งที่ไม่เข้าใจ แล้วฝึกต่อได้ตามจังหวะของตัวเอง',
    flow: 'เลือกครู → เลือกเรื่อง → แชตและฝึก → กลับมาต่อจากเดิม',
    demoNote: 'ต้นแบบในเบราว์เซอร์นี้ บทสนทนาเก็บในเครื่องคุณ และยังไม่ส่งขึ้นเชน',
    chooseTeacher: 'เลือกครู',
    continueLearning: 'เรียนต่อจากจุดเดิม',
    continueAction: 'เรียนต่อ',
    navHome: 'หน้าหลัก',
    navLearn: 'การเรียนของฉัน',
    navProfile: 'โปรไฟล์',
    back: 'ย้อนกลับ',
    free: 'เรียนฟรี',
    paid: 'บทเรียนเพิ่ม',
    samplePrice: 'ราคาตัวอย่าง',
    startChat: 'เริ่มคุย',
    lessons: 'เรื่องที่เรียนได้',
    howTheyTeach: 'วิธีที่ครูคนนี้สอน',
    goal: 'เป้าหมายของบท',
    passRule: 'ผ่านเมื่อ',
    locked: 'ยังไม่ปลดล็อก',
    inProgress: 'กำลังเรียน',
    notStarted: 'ยังไม่เริ่ม',
    passed: 'เรียนจบแล้ว',
    openLesson: 'เข้าบทเรียน',
    unlock: 'ปลดล็อกบทนี้',
    hint: 'ขอคำใบ้',
    explain: 'อธิบายอีกแบบ',
    attach: 'แนบรูป',
    send: 'ส่งข้อความ',
    messageLabel: 'ข้อความถึงครู',
    placeholder: 'พิมพ์คำถามหรือคำตอบ',
    emptySend: 'พิมพ์ข้อความก่อนส่ง',
    typing: 'กำลังตอบ',
    step: 'ขั้นที่',
    of: 'จาก',
    lessonDone: 'เรียนจบบทนี้แล้ว',
    nextLesson: 'ไปบทถัดไป',
    backToTopics: 'เลือกเรื่องอื่น',
    fillExample: 'ใส่ตัวอย่างในช่องข้อความ',
    myLearning: 'การเรียนของฉัน',
    myLearningLead: 'กลับมาต่อจากความคืบหน้าที่บันทึกไว้ในเครื่องนี้',
    emptyLearning: 'ยังไม่มีบทเรียนที่เริ่มไว้',
    pickTeacher: 'เลือกครูคนแรก',
    profile: 'โปรไฟล์',
    profileLead: 'ชื่อนี้ใช้ในแอปเท่านั้น และเปลี่ยนได้ทุกเมื่อ',
    displayName: 'ชื่อที่แสดง',
    language: 'ภาษาในแอป',
    thai: 'ไทย',
    english: 'English',
    wallet: 'กระเป๋าสำหรับบทเรียนเพิ่ม',
    walletOff: 'ยังไม่ได้เชื่อมต่อ บทเรียนฟรีใช้ได้โดยไม่ต้องมีกระเป๋า',
    walletOn: 'เชื่อมต่อแล้ว',
    connect: 'เชื่อมกระเป๋าเดโม',
    disconnect: 'เลิกเชื่อม',
    reset: 'ล้างข้อมูลเดโมในเครื่องนี้',
    resetDone: 'ล้างข้อมูลแล้ว',
    unlockedTitle: 'บทที่ปลดล็อกแล้ว',
    noUnlock: 'ยังไม่มีบทที่ซื้อในเดโมนี้',
    until: 'เข้าได้ถึง',
    unlockTitle: 'ปลดล็อกบทเรียน',
    unlockLead: 'บทฟรีเริ่มได้ทันที บทเพิ่มเติมในเดโมนี้ใช้การชำระจำลองด้วย USDC',
    youGet: 'ซื้อแล้วได้อะไร',
    accessFor: 'เข้าบทนี้ได้ 90 วัน ในเบราว์เซอร์นี้',
    offchain: 'บทสนทนาและความคืบหน้าเก็บในเครื่อง ไม่ได้เขียนลง Solana',
    revenueNote: 'แบบจริงจะผูกสิทธิ์กับกระเป๋า และแบ่งรายได้ให้ผู้สร้างเนื้อหา เดโมนี้ยังไม่โอนเงิน',
    priceLabel: 'ราคาตัวอย่าง',
    pay: 'จำลองการชำระด้วย USDC',
    paying: 'กำลังจำลองการยืนยันธุรกรรม',
    payFail: 'จำลองการชำระไม่สำเร็จ',
    needWallet: 'เชื่อมกระเป๋าเดโมก่อน จึงจะลองขั้นตอนชำระได้',
    payOkTitle: 'การชำระจำลองสำเร็จ',
    payOkBody: 'ปลดล็อกบทนี้ในเบราว์เซอร์แล้ว ยังไม่มีธุรกรรมจริงบน Solana',
    payBadTitle: 'การชำระจำลองไม่สำเร็จ',
    payBadBody: 'ยังไม่ได้ปลดล็อกบทนี้ ลองใหม่ได้โดยไม่เสียเงินจริง',
    enterLesson: 'เข้าห้องแชต',
    tryAgain: 'กลับไปลองใหม่',
    notFound: 'ไม่พบหน้าที่ต้องการ',
    backHome: 'กลับหน้าเลือกครู',
    daysLeft: 'เหลือสิทธิ์ในเดโม',
    example: 'ตัวอย่าง',
  },
  en: {
    brand: 'melearn chat',
    tagline: 'Talk with the right teacher. Learn your way.',
    intro: 'Pick a teacher, ask what you do not understand, and practice at your own pace.',
    flow: 'Choose a teacher → pick a topic → chat and practice → resume where you left off',
    demoNote: 'This browser prototype keeps the conversation on your device. Nothing is written on-chain.',
    chooseTeacher: 'Choose a teacher',
    continueLearning: 'Resume where you left off',
    continueAction: 'Continue',
    navHome: 'Home',
    navLearn: 'My learning',
    navProfile: 'Profile',
    back: 'Back',
    free: 'Free',
    paid: 'Extra lesson',
    samplePrice: 'Sample price',
    startChat: 'Start chat',
    lessons: 'Topics',
    howTheyTeach: 'How this teacher works',
    goal: 'Lesson goal',
    passRule: 'You pass when',
    locked: 'Locked',
    inProgress: 'In progress',
    notStarted: 'Not started',
    passed: 'Completed',
    openLesson: 'Open lesson',
    unlock: 'Unlock this lesson',
    hint: 'Hint',
    explain: 'Explain another way',
    attach: 'Attach image',
    send: 'Send',
    messageLabel: 'Message to the teacher',
    placeholder: 'Type a question or an answer',
    emptySend: 'Type a message before sending',
    typing: 'Replying',
    step: 'Step',
    of: 'of',
    lessonDone: 'You finished this lesson',
    nextLesson: 'Next lesson',
    backToTopics: 'Other topics',
    fillExample: 'Put an example in the box',
    myLearning: 'My learning',
    myLearningLead: 'Continue from the progress saved on this device',
    emptyLearning: 'No lessons started yet',
    pickTeacher: 'Choose your first teacher',
    profile: 'Profile',
    profileLead: 'This name stays in the app and you can change it anytime.',
    displayName: 'Display name',
    language: 'App language',
    thai: 'ไทย',
    english: 'English',
    wallet: 'Wallet for extra lessons',
    walletOff: 'Not connected. Free lessons work without a wallet.',
    walletOn: 'Connected',
    connect: 'Connect demo wallet',
    disconnect: 'Disconnect',
    reset: 'Clear demo data on this device',
    resetDone: 'Demo data cleared',
    unlockedTitle: 'Unlocked lessons',
    noUnlock: 'No purchased lessons in this demo yet',
    until: 'Access until',
    unlockTitle: 'Unlock a lesson',
    unlockLead: 'Free lessons start immediately. Extra lessons in this demo use a simulated USDC payment.',
    youGet: 'What you get',
    accessFor: '90 days of access to this lesson in this browser',
    offchain: 'Chat and progress stay on this device. They are not written to Solana.',
    revenueNote: 'A production version would tie access to a wallet and share revenue with the content creator. This demo does not move money.',
    priceLabel: 'Sample price',
    pay: 'Simulate a USDC payment',
    paying: 'Simulating transaction confirmation',
    payFail: 'Simulate a failed payment',
    needWallet: 'Connect the demo wallet before trying the payment step.',
    payOkTitle: 'Simulated payment succeeded',
    payOkBody: 'This lesson is unlocked in the browser. No real Solana transaction was sent.',
    payBadTitle: 'Simulated payment failed',
    payBadBody: 'This lesson is still locked. You can try again without spending real money.',
    enterLesson: 'Enter the chat',
    tryAgain: 'Try again',
    notFound: 'That page is not here',
    backHome: 'Back to teachers',
    daysLeft: 'Demo access left',
    example: 'Example',
  },
};

export function t(lang, key) {
  return copy[lang]?.[key] ?? copy.th[key] ?? key;
}
