/** Canonical Draft HTTP types come from OpenAPI; runtime validators remain separate. */
export type {
  WireLearningEnrollment,
  WireLearningItem,
  WireLearningCourse,
  WireLearningItemContent,
  WireAttemptQuestion,
  WireAttemptView,
  WireGradingQueueItem,
  WirePaymentView,
  WireCheckoutResult,
  WireRedeemResult,
  WireServerCertificate,
  WireAiConversation,
  WireAiOption,
  WireAiPracticeQuestion,
  WireAiMessage,
  WireAiUsage,
  WireAiContextCourse,
  WireAiPracticeAnswer,
  WireAdminAiCourse,
  WireAdminAiVideo,
  WireAdminAiAuthoring,
  WireAdminTranscript,
  WireRedeemAdminCourse,
  WireAdminRedeemCode,
  WireAdminPayment,
} from './generated/types.gen.ts';
